# Form implementation generated from reading ui file 'AlertView.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class AlertView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 306)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dropShadowFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.alert_frame = QtWidgets.QFrame(self.dropShadowFrame)
        self.alert_frame.setStyleSheet("background-color: rgb(56, 58, 89);\n"
"color: rgb(254, 121, 199);\n"
"font-family: Roboto;")
        self.alert_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.alert_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.alert_frame.setObjectName("alert_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.alert_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_frame = QtWidgets.QFrame(self.alert_frame)
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.title_frame)
        self.message_frame = QtWidgets.QFrame(self.alert_frame)
        self.message_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.message_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.message_frame.setObjectName("message_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.message_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.message_label = QtWidgets.QLabel(self.message_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.message_label.setFont(font)
        self.message_label.setStyleSheet("color: #fff")
        self.message_label.setText("")
        self.message_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.message_label.setObjectName("message_label")
        self.verticalLayout_4.addWidget(self.message_label)
        self.verticalLayout_3.addWidget(self.message_frame)
        self.btn_frame = QtWidgets.QFrame(self.alert_frame)
        self.btn_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btn_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_accept = QtWidgets.QPushButton(self.btn_frame)
        self.btn_accept.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_accept.setStyleSheet("QPushButton{\n"
"    background-color: rgb(254, 121, 199);\n"
"    color:#fff;\n"
"    border: none;\n"
"     border-radius: 20px;\n"
"    font-weight: Bold;\n"
"    font-family: Roboto Black;\n"
"    min-width: 100px;\n"
"    min-height: 40px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(214,101,169);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    font-weight: Bold\n"
"}")
        self.btn_accept.setObjectName("btn_accept")
        self.horizontalLayout.addWidget(self.btn_accept)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.btn_frame)
        self.verticalLayout_2.addWidget(self.alert_frame)
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "¡Atención!"))
        self.btn_accept.setText(_translate("MainWindow", "Aceptar"))
